### ISSUE TITLE
Any plans on making a ROS 2 package of MPOPIS? Question regarding time performance

### ISSUE THREAD

**Issue by Mechazo11** [sisl/MPOPIS#13]
Dear authors,
Awesome work with the MPOPIS framework as open source.

I was wondering about the following

1. Is there any plans on making MPOPIS compatible with ROS 2 by making a C++/python package?
2. With the given five AIS, does any variant of MPOPIS run in real-time speed? 

Thank you for your time.

With best regards,
@Mechazo11

**Comment by dylan-asmar** [comment]
Thank you!

We currently do not have any plans to make it compatible with ROS2. There are some great implementations of different variants of MPPI (though not including MPOPIS, yet) that are compatible or easy to integrate with ROS2. Of note, https://github.com/ACDSLab/MPPI-Generic shows great performance when compared to different implementations and hardware here: https://acdslab.github.io/mppi-generic-website/benchmarks.

Depending on your control frequency requirements, there could definitely be variants of MPOPIS that could run in real-time. Using Figure 1 from the benchmarks page linked above, depending on the implementation details, I'd expect to be able to perform multiple iterations of AIS and still be able to achieve a 100HZ control rate.

Let me know if you plan to extend some implementations that already exist or work on your own. I'd be happy to provide any input that I could!

**Comment by Mechazo11** [comment]
@dylan-asmar thank you very much getting back to my query. Yes I am aware of MPPI-Generic and am currently making a ROS 2 package for it for use in a robotics project. If I am successfully in that regard, I will share my findings with you for a possible ROS 2 package for MPOPIS.
