### ISSUE TITLE
Package precompile failed

### ISSUE THREAD

**Issue by YihanLi126** [sisl/MPOPIS#6]
After I installed the package, it shows that the precompile of Conda, Pycall and MPOPIS failed, then I precompiled it again and got this:
<img width="588" alt="precompile_fail" src="https://user-images.githubusercontent.com/112290359/232695170-d5fe3c18-223e-45e2-9a43-d753f9ba2700.png">
To solve the problem, I first reinstalled Conda and PyCall:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/112290359/232695643-597d5fac-bfd9-4126-8c43-17097b2294ad.png">
And then reinstalled MPOPIS. PyCall and Conda worked this time, but MPOPIS still failed the precompile:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/112290359/232697203-122c8a01-3407-4cc6-92e7-0b1fd90ab0d7.png">
Is there anything wrong? Did I forget anything in the installation?

**Comment by YihanLi126** [comment]
An update: Since there is no information about PyCall and Conda after I reinstalled MPOPIS, I precompiled them again and found they still didn't work:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/112290359/232698340-caca2517-e967-40ab-a3ec-a608dcfb2b87.png">

**Comment by dylan-asmar** [comment]
@YihanLi126 Any suggestions on how to prevent this in the future? I don't think I have run into this before.

**Comment by dylan-asmar** [comment]
I haven't been able to recreate this problem. Please reopen if you see this again.
